component: express
name: express
app: express-mongodb
stage: dev
inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    environment:
      variables:
        MONGODB_CONNECT_STRING: ${env:MONGODB_CONNECT_STRING}
        ALI_SECRET_ID: ${env:ALI_SECRET_ID}
        ALI_SECRET_KEY: ${env:ALI_SECRET_KEY}
        SendKey: ${env:SendKey}
    eip: false
    timeout: 30
    memorySize: 128
