name: deploy CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGODB_CONNECT_STRING: ${{ secrets.MONGODB_CONNECT_STRING }}
